/*
CREATE TABLE NASDA.TB_corr_Design_Summary (
    e_DesignGuid NVARCHAR(100),
    e_version NVARCHAR(50),
    e_projectId NVARCHAR(50),
    e_dashno NVARCHAR(50),
    e_designquantity INT,
    e_savedcost DECIMAL(18, 2),
    e_savedprice DECIMAL(18, 2),
    e_factorydiscount DECIMAL(18, 2),
    e_active INT,
    e_saveddate DATETIME,
    eAirTunnel NVARCHAR(50),
    eApplication NVARCHAR(50),
    eCesFan NVARCHAR(50),
    eCoil_CW NVARCHAR(50),
    eCoil_DX NVARCHAR(50),
    eCoil_HW NVARCHAR(50),
    eCoil_IFB NVARCHAR(50),
    eCoil_Steam NVARCHAR(50),
    eComponent NVARCHAR(50),
    eDirectFiredGas NVARCHAR(50),
    eDoor NVARCHAR(50),
    eDrain NVARCHAR(50),
    eDrawingElement NVARCHAR(50),
    eDrawingSheet NVARCHAR(50),
    eEconomizer NVARCHAR(50),
    eElecPanel NVARCHAR(50),
    eElecSwitch NVARCHAR(50),
    eElectricHeat NVARCHAR(50),
    eEvapCooling NVARCHAR(50),
    eFanwall NVARCHAR(50),
    eFilter NVARCHAR(50),
    eGage NVARCHAR(50),
    eHeatPipe NVARCHAR(50),
    eHeatWheel NVARCHAR(50),
    eHumidifier NVARCHAR(50),
    eIndirectFiredGas NVARCHAR(50),
    eInternalWall NVARCHAR(50),
    eLight NVARCHAR(50),
    eOpening NVARCHAR(50),
    ePlateExchanger NVARCHAR(50),
    eProject NVARCHAR(50),
    eSection NVARCHAR(50),
    eSoundTrap NVARCHAR(50),
    eUVLight NVARCHAR(50),
    eView NVARCHAR(50),
    eDimensionLevel NVARCHAR(50),
    eProxyAirTunnel NVARCHAR(50),
    eTestMisc NVARCHAR(50),
    eTestComponent NVARCHAR(50),
    eUserData NVARCHAR(50),
    eCompanyBrand NVARCHAR(50),
    eAddDeduct NVARCHAR(50),
    eManagedOpening NVARCHAR(50),
    eSubmittalNote NVARCHAR(50),
    eSubmittalNoteBlock NVARCHAR(50),
    eSubmittalNoteBlockItem NVARCHAR(50),
    eSubmittalHeader NVARCHAR(50),
    eProjectHeader NVARCHAR(50),
    eSubmittalRevision NVARCHAR(50),
    eElectricalConnection NVARCHAR(50),
    eCondition NVARCHAR(50),
    eDesignCondition NVARCHAR(50),
    eDesignComponentCondition NVARCHAR(50),
    eCondenser NVARCHAR(50),
    eGasHeatExchanger NVARCHAR(50),
    eSelectionCoil NVARCHAR(50),
    eSelectionCondenser NVARCHAR(50),
    eSelectionIndirectFiredGas NVARCHAR(50),
    eSelectionCircuitRatio NVARCHAR(50),
    eSubmittalSection NVARCHAR(50),
    eSubmittalBlock NVARCHAR(50),
    eSubmittalElement NVARCHAR(50),
    eSelectionIndirectFiredGasOption NVARCHAR(50),
    eSelectionAirMixer NVARCHAR(50),
    eHousedFan NVARCHAR(50),
    ePlenumFan NVARCHAR(50),
    eSelectionPlenumFan NVARCHAR(50),
    eSelectionHousedFan NVARCHAR(50),
    eSelectionHeatWheel NVARCHAR(50),
    eSelectionHumidifierValve NVARCHAR(50),
    eSelectionHumidifierSteamGen NVARCHAR(50),
    eSelectionHumidifierFrame NVARCHAR(50),
    eUserDefinedComponent NVARCHAR(50),
    eFileSearch NVARCHAR(50),
    eFanArray NVARCHAR(50),
    eSelectionFanArray NVARCHAR(50),
    eCondenserDX NVARCHAR(50),
    eSelectionCondenserCoils NVARCHAR(50),
    eAirflowObject NVARCHAR(50),
    eAirflowObjectConnector NVARCHAR(50),
    eAirflowObjectConnectorAirflow NVARCHAR(50),
    eProjectHistory NVARCHAR(50),
    eContact NVARCHAR(50),
    eLiftingLug NVARCHAR(50),
    eEngineeringScheduleComponent NVARCHAR(50),
    eEngineeringScheduleProperty NVARCHAR(50),
    eEngineeringSchedule NVARCHAR(50),
    eCoil_HotGasReheat NVARCHAR(50),
    eCondenserRBE NVARCHAR(50),
    eEndwall NVARCHAR(50),
    ePartition NVARCHAR(50),
    ePlenum NVARCHAR(50),
    eSplit NVARCHAR(50)
);
*/
/*
truncate TABLE NASDA.TB_corr_Design_Summary
INSERT INTO NASDA.TB_corr_Design_Summary
(
e_DesignGuid ,
    e_version ,
    e_projectId ,
    e_dashno ,
    e_designquantity ,
    e_savedcost ,
    e_savedprice ,
    e_factorydiscount ,
    e_active ,
    e_saveddate ,
    eAirTunnel ,
    eApplication ,
    eCesFan ,
    eCoil_CW ,
    eCoil_DX ,
    eCoil_HW ,
    eCoil_IFB ,
    eCoil_Steam ,
    eComponent ,
    eDirectFiredGas ,
    eDoor ,
    eDrain ,
    eDrawingElement ,
    eDrawingSheet ,
    eEconomizer ,
    eElecPanel ,
    eElecSwitch ,
    eElectricHeat ,
    eEvapCooling ,
    eFanwall ,
    eFilter ,
    eGage ,
    eHeatPipe ,
    eHeatWheel ,
    eHumidifier ,
    eIndirectFiredGas ,
    eInternalWall ,
    eLight ,
    eOpening ,
    ePlateExchanger ,
    eProject ,
    eSection ,
    eSoundTrap ,
    eUVLight ,
    eView ,
    eDimensionLevel ,
    eProxyAirTunnel ,
    eTestMisc ,
    eTestComponent ,
    eUserData ,
    eCompanyBrand ,
    eAddDeduct ,
    eManagedOpening ,
    eSubmittalNote ,
    eSubmittalNoteBlock ,
    eSubmittalNoteBlockItem ,
    eSubmittalHeader ,
    eProjectHeader ,
    eSubmittalRevision ,
    eElectricalConnection ,
    eCondition ,
    eDesignCondition ,
    eDesignComponentCondition ,
    eCondenser ,
    eGasHeatExchanger ,
    eSelectionCoil ,
    eSelectionCondenser ,
    eSelectionIndirectFiredGas ,
    eSelectionCircuitRatio ,
    eSubmittalSection ,
    eSubmittalBlock ,
    eSubmittalElement ,
    eSelectionIndirectFiredGasOption ,
    eSelectionAirMixer ,
    eHousedFan ,
    ePlenumFan ,
    eSelectionPlenumFan ,
    eSelectionHousedFan ,
    eSelectionHeatWheel ,
    eSelectionHumidifierValve ,
    eSelectionHumidifierSteamGen ,
    eSelectionHumidifierFrame ,
    eUserDefinedComponent ,
    eFileSearch ,
    eFanArray ,
    eSelectionFanArray ,
    eCondenserDX ,
    eSelectionCondenserCoils ,
    eAirflowObject ,
    eAirflowObjectConnector ,
    eAirflowObjectConnectorAirflow ,
    eProjectHistory ,
    eContact ,
    eLiftingLug ,
    eEngineeringScheduleComponent ,
    eEngineeringScheduleProperty ,
    eEngineeringSchedule ,
    eCoil_HotGasReheat ,
    eCondenserRBE ,
    eEndwall ,
    ePartition ,
    ePlenum ,
    eSplit 
	)

select 
               ad.DesignGuid as e_DesignGuid,
               ad.version as e_version,
               --cpd.max_version                                       as version,
               ad.projectID as e_projectId,
               ad.dashno as e_dashno,

               --ad.DesignGuid,
               --ad.DashNo,
               ad.DesignQty as e_designquantity,
               ad.savedcost as e_savedcost,
               ad.savedprice as e_savedprice,
               ad.factoryDiscount as e_factorydiscount,
               ad.Active as e_active,
               ad.saveddate as e_saveddate,
               dc.value('(eAirTunnel)[1]', 'NVARCHAR(50)')     as eAirTunnel,
               dc.value('(eApplication)[1]', 'NVARCHAR(50)')     as eApplication,
               dc.value('(eCesFan)[1]', 'NVARCHAR(50)')     as eCesFan,
               dc.value('(eCoil_CW)[1]', 'NVARCHAR(50)')     as eCoil_CW,
               dc.value('(eCoil_DX)[1]', 'NVARCHAR(50)')     as eCoil_DX,
               dc.value('(eCoil_HW)[1]', 'NVARCHAR(50)')     as eCoil_HW,
               dc.value('(eCoil_IFB)[1]', 'NVARCHAR(50)')     as eCoil_IFB,
               dc.value('(eCoil_Steam)[1]', 'NVARCHAR(50)')     as eCoil_Steam,
               dc.value('(eComponent)[1]', 'NVARCHAR(50)')     as eComponent,
               dc.value('(eDirectFiredGas)[1]', 'NVARCHAR(50)')     as eDirectFiredGas,
               dc.value('(eDoor)[1]', 'NVARCHAR(50)')     as eDoor,
               dc.value('(eDrain)[1]', 'NVARCHAR(50)')     as eDrain,
               dc.value('(eDrawingElement)[1]', 'NVARCHAR(50)')     as eDrawingElement,
               dc.value('(eDrawingSheet)[1]', 'NVARCHAR(50)')     as eDrawingSheet,
               dc.value('(eEconomizer)[1]', 'NVARCHAR(50)')     as eEconomizer,
               dc.value('(eElecPanel)[1]', 'NVARCHAR(50)')     as eElecPanel,
               dc.value('(eElecSwitch)[1]', 'NVARCHAR(50)')     as eElecSwitch,
               dc.value('(eElectricHeat)[1]', 'NVARCHAR(50)')     as eElectricHeat,
               dc.value('(eEvapCooling)[1]', 'NVARCHAR(50)')     as eEvapCooling,
               dc.value('(eFanwall)[1]', 'NVARCHAR(50)')     as eFanwall,
               dc.value('(eFilter)[1]', 'NVARCHAR(50)')     as eFilter,
               dc.value('(eGage)[1]', 'NVARCHAR(50)')     as eGage,
               dc.value('(eHeatPipe)[1]', 'NVARCHAR(50)')     as eHeatPipe,
               dc.value('(eHeatWheel)[1]', 'NVARCHAR(50)')     as eHeatWheel,
               dc.value('(eHumidifier)[1]', 'NVARCHAR(50)')     as eHumidifier,
               dc.value('(eIndirectFiredGas)[1]', 'NVARCHAR(50)')     as eIndirectFiredGas,
               dc.value('(eInternalWall)[1]', 'NVARCHAR(50)')     as eInternalWall,
               dc.value('(eLight)[1]', 'NVARCHAR(50)')     as eLight,
               dc.value('(eOpening)[1]', 'NVARCHAR(50)')     as eOpening,
               dc.value('(ePlateExchanger)[1]', 'NVARCHAR(50)')     as ePlateExchanger,
               dc.value('(eProject)[1]', 'NVARCHAR(50)')     as eProject,
               dc.value('(eSection)[1]', 'NVARCHAR(50)')     as eSection,
               dc.value('(eSoundTrap)[1]', 'NVARCHAR(50)')     as eSoundTrap,
               dc.value('(eUVLight)[1]', 'NVARCHAR(50)')     as eUVLight,
               dc.value('(eView)[1]', 'NVARCHAR(50)')     as eView,
               dc.value('(eDimensionLevel)[1]', 'NVARCHAR(50)')     as eDimensionLevel,
               dc.value('(eProxyAirTunnel)[1]', 'NVARCHAR(50)')     as eProxyAirTunnel,
               dc.value('(eTestMisc)[1]', 'NVARCHAR(50)')     as eTestMisc,
               dc.value('(eTestComponent)[1]', 'NVARCHAR(50)')     as eTestComponent,
               dc.value('(eUserData)[1]', 'NVARCHAR(50)')     as eUserData,
               dc.value('(eCompanyBrand)[1]', 'NVARCHAR(50)')     as eCompanyBrand,
               dc.value('(eAddDeduct)[1]', 'NVARCHAR(50)')     as eAddDeduct,
               dc.value('(eManagedOpening)[1]', 'NVARCHAR(50)')     as eManagedOpening,
               dc.value('(eSubmittalNote)[1]', 'NVARCHAR(50)')     as eSubmittalNote,
               dc.value('(eSubmittalNoteBlock)[1]', 'NVARCHAR(50)')     as eSubmittalNoteBlock,
               dc.value('(eSubmittalNoteBlockItem)[1]', 'NVARCHAR(50)')     as eSubmittalNoteBlockItem,
               dc.value('(eSubmittalHeader)[1]', 'NVARCHAR(50)')     as eSubmittalHeader,
               dc.value('(eProjectHeader)[1]', 'NVARCHAR(50)')     as eProjectHeader,
               dc.value('(eSubmittalRevision)[1]', 'NVARCHAR(50)')     as eSubmittalRevision,
               dc.value('(eElectricalConnection)[1]', 'NVARCHAR(50)')     as eElectricalConnection,
               dc.value('(eCondition)[1]', 'NVARCHAR(50)')     as eCondition,
               dc.value('(eDesignCondition)[1]', 'NVARCHAR(50)')     as eDesignCondition,
               dc.value('(eDesignComponentCondition)[1]', 'NVARCHAR(50)')     as eDesignComponentCondition,
               dc.value('(eCondenser)[1]', 'NVARCHAR(50)')     as eCondenser,
               dc.value('(eGasHeatExchanger)[1]', 'NVARCHAR(50)')     as eGasHeatExchanger,
               dc.value('(eSelectionCoil)[1]', 'NVARCHAR(50)')     as eSelectionCoil,
               dc.value('(eSelectionCondenser)[1]', 'NVARCHAR(50)')     as eSelectionCondenser,
               dc.value('(eSelectionIndirectFiredGas)[1]', 'NVARCHAR(50)')     as eSelectionIndirectFiredGas,
               dc.value('(eSelectionCircuitRatio)[1]', 'NVARCHAR(50)')     as eSelectionCircuitRatio,
               dc.value('(eSubmittalSection)[1]', 'NVARCHAR(50)')     as eSubmittalSection,
               dc.value('(eSubmittalBlock)[1]', 'NVARCHAR(50)')     as eSubmittalBlock,
               dc.value('(eSubmittalElement)[1]', 'NVARCHAR(50)')     as eSubmittalElement,
               dc.value('(eSelectionIndirectFiredGasOption)[1]', 'NVARCHAR(50)')     as eSelectionIndirectFiredGasOption,
               dc.value('(eSelectionAirMixer)[1]', 'NVARCHAR(50)')     as eSelectionAirMixer,
               dc.value('(eHousedFan)[1]', 'NVARCHAR(50)')     as eHousedFan,
               dc.value('(ePlenumFan)[1]', 'NVARCHAR(50)')     as ePlenumFan,
               dc.value('(eSelectionPlenumFan)[1]', 'NVARCHAR(50)')     as eSelectionPlenumFan,
               dc.value('(eSelectionHousedFan)[1]', 'NVARCHAR(50)')     as eSelectionHousedFan,
               dc.value('(eSelectionHeatWheel)[1]', 'NVARCHAR(50)')     as eSelectionHeatWheel,
               dc.value('(eSelectionHumidifierValve)[1]', 'NVARCHAR(50)')     as eSelectionHumidifierValve,
               dc.value('(eSelectionHumidifierSteamGen)[1]', 'NVARCHAR(50)')     as eSelectionHumidifierSteamGen,
               dc.value('(eSelectionHumidifierFrame)[1]', 'NVARCHAR(50)')     as eSelectionHumidifierFrame,
               dc.value('(eUserDefinedComponent)[1]', 'NVARCHAR(50)')     as eUserDefinedComponent,
               dc.value('(eFileSearch)[1]', 'NVARCHAR(50)')     as eFileSearch,
               dc.value('(eFanArray)[1]', 'NVARCHAR(50)')     as eFanArray,
               dc.value('(eSelectionFanArray)[1]', 'NVARCHAR(50)')     as eSelectionFanArray,
               dc.value('(eCondenserDX)[1]', 'NVARCHAR(50)')     as eCondenserDX,
               dc.value('(eSelectionCondenserCoils)[1]', 'NVARCHAR(50)')     as eSelectionCondenserCoils,
               dc.value('(eAirflowObject)[1]', 'NVARCHAR(50)')     as eAirflowObject,
               dc.value('(eAirflowObjectConnector)[1]', 'NVARCHAR(50)')     as eAirflowObjectConnector,
               dc.value('(eAirflowObjectConnectorAirflow)[1]', 'NVARCHAR(50)')     as eAirflowObjectConnectorAirflow,
               dc.value('(eProjectHistory)[1]', 'NVARCHAR(50)')     as eProjectHistory,
               dc.value('(eContact)[1]', 'NVARCHAR(50)')     as eContact,
               dc.value('(eLiftingLug)[1]', 'NVARCHAR(50)')     as eLiftingLug,
               dc.value('(eEngineeringScheduleComponent)[1]', 'NVARCHAR(50)')     as eEngineeringScheduleComponent,
               dc.value('(eEngineeringScheduleProperty)[1]', 'NVARCHAR(50)')     as eEngineeringScheduleProperty,
               dc.value('(eEngineeringSchedule)[1]', 'NVARCHAR(50)')     as eEngineeringSchedule,
               dc.value('(eCoil_HotGasReheat)[1]', 'NVARCHAR(50)')     as eCoil_HotGasReheat,
               dc.value('(eCondenserRBE)[1]', 'NVARCHAR(50)')     as eCondenserRBE,
               dc.value('(eEndwall)[1]', 'NVARCHAR(50)')     as eEndwall,
               dc.value('(ePartition)[1]', 'NVARCHAR(50)')     as ePartition,
               dc.value('(ePlenum)[1]', 'NVARCHAR(50)')     as ePlenum,
               dc.value('(eSplit)[1]', 'NVARCHAR(50)')     as eSplit
               
               
           from
               NASDA.DA_Design                           as ad
               cross APPLY ad.data.nodes('Design/cNextNames') as design(dc)
               where ad.Active = 1

        */

select * from NASDA.TB_corr_Design_Summary