/*
CREATE TABLE NASDA.TB_corr_Project_Details (
    p_ProjectID NVARCHAR(50),
    p_version NVARCHAR(50),
    p_savedDate DATETIME,
    p_active int,
    p_HdaVersion NVARCHAR(50),
    p_RedFirm NVARCHAR(150),
    p_TotalPrice DECIMAL(18, 2),
    p_Brand NVARCHAR(50),
    p_ProjectStage NVARCHAR(50),
    p_Name NVARCHAR(50),
    p_MarketSegment NVARCHAR(50),
    p_BuildingUse NVARCHAR(50),
    p_ProjectConstruction NVARCHAR(50),
    p_RepCompanyName NVARCHAR(50),
    p_ProjectType NVARCHAR(50),
    p_ContractSpecification NVARCHAR(50),
    p_ProjectedShipQuarter NVARCHAR(50),
    p_CRMOpportunityGUID NVARCHAR(50),
    p_ProjectCurrency NVARCHAR(50),
    p_CleaningWrapping NVARCHAR(50),
    p_ClimateZone NVARCHAR(50),
    p_CustomerCity NVARCHAR(50),
    p_CustomerCountry NVARCHAR(50),
    p_CustomerState NVARCHAR(50),
    p_CustomerZipCode NVARCHAR(50),
    p_Elevation NVARCHAR(50),
    p_DSBreakoutCommission NVARCHAR(50),
    p_DSBreakoutContractorPOPremium NVARCHAR(50),
    p_DSCenterOfGravity NVARCHAR(50),
    p_DSCompChannelBlender NVARCHAR(50),
    p_DSCompCoilDataSheets NVARCHAR(50),
    p_DSCompCondenser NVARCHAR(50),
    p_DSCompElectricalLayout NVARCHAR(50),
    p_DSCompElectricHeaters NVARCHAR(50),
    p_DSCompFanDataSheets NVARCHAR(50),
    p_DSCompFilter NVARCHAR(50),
    p_DSCompGasHeaters NVARCHAR(50),
    p_DSCompHumidifiers NVARCHAR(50),
    p_DSCompSoundTrap NVARCHAR(50),
    p_DSCompUserDefinedComponent NVARCHAR(50),
    p_DSCostEstimate NVARCHAR(50),
    p_DSCoverPage NVARCHAR(50),
    p_DSCreateSeparateReports NVARCHAR(50),
    p_DSHeat NVARCHAR(50),
    p_DSIncludeAllDesigns NVARCHAR(50),
    p_DSIncludePageNumbers NVARCHAR(50),
    p_DSLineItemSummary NVARCHAR(50),
    p_DSLineItemSummaryIncludePricing NVARCHAR(50),
    p_DSOpenSeparateReports NVARCHAR(50),
    p_DSPower NVARCHAR(50),
    p_DSPricingProposal NVARCHAR(50),
    p_DSPricingProposalIncludeFreight NVARCHAR(50),
    p_DSPricingProposalWord NVARCHAR(50),
    p_DSSeparateReportPath NVARCHAR(50),
    p_DSSoundPower NVARCHAR(50),
    p_DSStaticPressure NVARCHAR(50),
    p_DSSummarySheet NVARCHAR(50),
    p_DSSummarySheetWord NVARCHAR(50)
);
*/

INSERT INTO NASDA.TB_corr_Project_Details (
    p_ProjectID,
    p_version,
    p_savedDate,
    p_active,
    p_HdaVersion,
    p_RedFirm,
    p_TotalPrice,
    p_Brand,
    p_ProjectStage,
    p_Name,
    p_MarketSegment,
    p_BuildingUse,
    p_ProjectConstruction,
    p_RepCompanyName,
    p_ProjectType,
    p_ContractSpecification,
    p_ProjectedShipQuarter,
    p_CRMOpportunityGUID,
    p_ProjectCurrency,
    p_CleaningWrapping,
    p_ClimateZone,
    p_CustomerCity,
    p_CustomerCountry,
    p_CustomerState,
    p_CustomerZipCode,
    p_Elevation,
    p_DSBreakoutCommission,
    p_DSBreakoutContractorPOPremium,
    p_DSCenterOfGravity,
    p_DSCompChannelBlender,
    p_DSCompCoilDataSheets,
    p_DSCompCondenser,
    p_DSCompElectricalLayout,
    p_DSCompElectricHeaters,
    p_DSCompFanDataSheets,
    p_DSCompFilter,
    p_DSCompGasHeaters,
    p_DSCompHumidifiers,
    p_DSCompSoundTrap,
    p_DSCompUserDefinedComponent,
    p_DSCostEstimate,
    p_DSCoverPage,
    p_DSCreateSeparateReports,
    p_DSHeat,
    p_DSIncludeAllDesigns,
    p_DSIncludePageNumbers,
    p_DSLineItemSummary,
    p_DSLineItemSummaryIncludePricing,
    p_DSOpenSeparateReports,
    p_DSPower,
    p_DSPricingProposal,
    p_DSPricingProposalIncludeFreight,
    p_DSPricingProposalWord,
    p_DSSeparateReportPath,
    p_DSSoundPower,
    p_DSStaticPressure,
    p_DSSummarySheet,
    p_DSSummarySheetWord
)
SELECT
               dp.ProjectID as p_ProjectID,
               dp.version as p_version,
               dp.SavedDate as p_savedDate,
               dp.active as p_active,
               dp.HdaVersion as p_HdaVersion,
               dp.RepFirm as p_RedFirm,
               --cp.max_version                                        as version,
               --dpt.QuoteNumber,
               --dpt.SONumber,
               --dpt.HideProject,
               --dpt.SubmittedToFactoryDate, 
               dp.totalprice as p_TotalPrice,
               p.value('(Brand)[1]', 'NVARCHAR(50)')                 AS 'p_Brand',
               p.value('(ProjectStage)[1]', 'NVARCHAR(50)')          AS 'p_ProjectStage',
               p.value('(Name)[1]', 'NVARCHAR(50)')                  AS 'p_Name',
               p.value('(MarketSegment)[1]', 'NVARCHAR(50)')         AS 'p_MarketSegment',
               p.value('(BuildingUse)[1]', 'NVARCHAR(50)')           AS 'p_BuildingUse',
               p.value('(ProjectConstruction)[1]', 'NVARCHAR(50)')   AS 'p_ProjectConstruction',
               p.value('(RepCompanyName)[1]', 'NVARCHAR(50)')        AS 'p_RepCompanyName',
               p.value('(ProjectType)[1]', 'NVARCHAR(50)')           AS 'p_ProjectType',
               p.value('(ContractSpecification)[1]', 'NVARCHAR(50)') AS 'p_ContractSpecification',
               p.value('(ProjectedShipQuarter)[1]', 'NVARCHAR(50)')  AS 'p_ProjectedShipQuarter',
               p.value('(CRMOpportunityGUID)[1]', 'NVARCHAR(50)')    AS 'p_CRMOpportunityGUID',
               p.value('(ProjectCurrency)[1]', 'NVARCHAR(50)')       AS 'p_ProjectCurrency',
               p.value('(CleaningWrapping)[1]', 'NVARCHAR(50)')                 AS 'p_CleaningWrapping',
               p.value('(ClimateZone)[1]', 'NVARCHAR(50)')                 AS 'p_ClimateZone',
               p.value('(CustomerCity)[1]', 'NVARCHAR(50)')                 AS 'p_CustomerCity',
               p.value('(CustomerCountry)[1]', 'NVARCHAR(50)')                 AS 'p_CustomerCountry',
               p.value('(CustomerState)[1]', 'NVARCHAR(50)')                 AS 'p_CustomerState',
               p.value('(CustomerZipCode)[1]', 'NVARCHAR(50)')                 AS 'p_CustomerZipCode',
               p.value('(Elevation)[1]', 'NVARCHAR(50)')                 AS 'p_Elevation',
               p.value('(DSBreakoutCommission)[1]', 'NVARCHAR(50)')                 AS 'p_DSBreakoutCommission',
               p.value('(DSBreakoutContractorPOPremium)[1]', 'NVARCHAR(50)')                 AS 'p_DSBreakoutContractorPOPremium',
               p.value('(DSCenterOfGravity)[1]', 'NVARCHAR(50)')                 AS 'p_DSCenterOfGravity',
               p.value('(DSCompChannelBlender)[1]', 'NVARCHAR(50)')                 AS 'p_DSCompChannelBlender',
               p.value('(DSCompCoilDataSheets)[1]', 'NVARCHAR(50)')                 AS 'p_DSCompCoilDataSheets',
               p.value('(DSCompCondenser)[1]', 'NVARCHAR(50)')                 AS 'p_DSCompCondenser',
               p.value('(DSCompElectricalLayout)[1]', 'NVARCHAR(50)')                 AS 'p_DSCompElectricalLayout',
               p.value('(DSCompElectricHeaters)[1]', 'NVARCHAR(50)')                 AS 'p_DSCompElectricHeaters',
               p.value('(DSCompFanDataSheets)[1]', 'NVARCHAR(50)')                 AS 'p_DSCompFanDataSheets',
               p.value('(DSCompFilter)[1]', 'NVARCHAR(50)')                 AS 'p_DSCompFilter',
               p.value('(DSCompGasHeaters)[1]', 'NVARCHAR(50)')                 AS 'p_DSCompGasHeaters',
               p.value('(DSCompHumidifiers)[1]', 'NVARCHAR(50)')                 AS 'p_DSCompHumidifiers',
               p.value('(DSCompSoundTrap)[1]', 'NVARCHAR(50)')                 AS 'p_DSCompSoundTrap',
               p.value('(DSCompUserDefinedComponent)[1]', 'NVARCHAR(50)')                 AS 'p_DSCompUserDefinedComponent',
               p.value('(DSCostEstimate)[1]', 'NVARCHAR(50)')                 AS 'p_DSCostEstimate',
               p.value('(DSCoverPage)[1]', 'NVARCHAR(50)')                 AS 'p_DSCoverPage',
               p.value('(DSCreateSeparateReports)[1]', 'NVARCHAR(50)')                 AS 'p_DSCreateSeparateReports',
               p.value('(DSHeat)[1]', 'NVARCHAR(50)')                 AS 'p_DSHeat',
               p.value('(DSIncludeAllDesigns)[1]', 'NVARCHAR(50)')                 AS 'p_DSIncludeAllDesigns',
               p.value('(DSIncludePageNumbers)[1]', 'NVARCHAR(50)')                 AS 'p_DSIncludePageNumbers',
               p.value('(DSLineItemSummary)[1]', 'NVARCHAR(50)')                 AS 'p_DSLineItemSummary',
               p.value('(DSLineItemSummaryIncludePricing)[1]', 'NVARCHAR(50)')                 AS 'p_DSLineItemSummaryIncludePricing',
               p.value('(DSOpenSeparateReports)[1]', 'NVARCHAR(50)')                 AS 'p_DSOpenSeparateReports',
               p.value('(DSPower)[1]', 'NVARCHAR(50)')                 AS 'p_DSPower',
               p.value('(DSPricingProposal)[1]', 'NVARCHAR(50)')                 AS 'p_DSPricingProposal',
               p.value('(DSPricingProposalIncludeFreight)[1]', 'NVARCHAR(50)')                 AS 'p_DSPricingProposalIncludeFreight',
               p.value('(DSPricingProposalWord)[1]', 'NVARCHAR(50)')                 AS 'p_DSPricingProposalWord',
               p.value('(DSSeparateReportPath)[1]', 'NVARCHAR(50)')                 AS 'p_DSSeparateReportPath',
               p.value('(DSSoundPower)[1]', 'NVARCHAR(50)')                 AS 'p_DSSoundPower',
               p.value('(DSStaticPressure)[1]', 'NVARCHAR(50)')                 AS 'p_DSStaticPressure',
               p.value('(DSSummarySheet)[1]', 'NVARCHAR(50)')                 AS 'p_DSSummarySheet',
               p.value('(DSSummarySheetWord)[1]', 'NVARCHAR(50)')                 AS 'p_DSSummarySheetWord'
               


           FROM
               nasda.DA_Project as dp
               CROSS APPLY dp.ProjectData.nodes('Project/Project') AS projectdetail(p)



/*
ALTER TABLE NASDA.TB_corr_Project_Details

ALTER COLUMN p_RedFirm NVARCHAR(150);
*/